sudo: required
language: python
os: linux
dist: trusty
python: 3.4
matrix:
  fast_finish: true
  include:
    - addons:
        chrome: beta
      env: INFO="chrome beta" BROWSER=google-chrome-beta
    - addons:
        chrome: stable
      env: INFO="chrome stable" BROWSER=google-chrome-stable
    - addons:
        firefox: latest
      env: INFO="firefox" BROWSER=firefox
    - addons:
        firefox: latest-esr
      env: INFO="firefox esr" BROWSER=firefox
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-utils
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script: travis_retry ./setup_travis.sh
script: . ./run_travis.sh
